<?php

// TRABALHO DA UC_9

// - No index.php o script faz uma requisição ao arquivo api.php, que retorna dados em formato JSON sobre carros. 
// Em seguida, cria e inseri no HTML as informações de cada carro na página.
// Isso permite exibir a lista de carros de forma  atualizada.

// O código PHP conecta-se a um banco de dados MySQL chamado "carros" e consulta todos os registros da tabela "modelos_carros".
// Ele armazena os dados em um array e, ao final, fecha a conexão.
// Script retorna os dados em formato JSON, definindo o cabeçalho apropriado para que possam ser usados por um cliente, como uma aplicação JavaScript.

?>


